user:
  token: xxx

node:
  sensor: analog
  param: analog
  token: xxx

app:
  baseurl: https://us.wio.seeed.io/
  schedule: 15
  db_name: 'leetbase'
  db_host: 'localhost'
  db_port: 8086
  sensor_tag: soil1