user:
  token: SHFJSRtqRmgaRRQZ

node:
  sensor: analog
  param: analog
  token: 6bb3a73ba99502614dc1abed69d8da01

app:
  baseurl: https://us.wio.seeed.io/
  schedule: 15
  db_name: 'leetbase'
  db_host: 'localhost'
  db_port: 8086
  sensor_tag: soil1