secrets:
  USER_TOKEN: SHFJSRtqRmgaRRQZ
  NODE_TOKEN: 6bb3a73ba99502614dc1abed69d8da01

configmap:
  BASE_URL: https://us.wio.seeed.io/
  DB_NAME: 'leetbase'
  DB_HOST: 'localhost'
  DB_PORT: 8086
  NODE_SENSOR: 'analog'
  NODE_PARAM: 'analog'
  NODE_SCHEDULE: 5

image:
  repository: docker.io/dukeman/wioleet_v2
  tag: latest