apiVersion: v1
kind: ConfigMap
metadata:
  name: wioleet-configmap
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    app: {{ template "fullname" . }}
data:
  {{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}