apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: USER_TOKEN
          valueFrom:
            secretKeyRef:
              name: wioleet-secrets
              key: USER_TOKEN
        - name: NODE_TOKEN
          valueFrom:
            secretKeyRef:
              name: wioleet-secrets
              key: NODE_TOKEN
        - name: BASE_URL
          valueFrom:
            secretKeyRef:
              name: wioleet-secrets
              key: BASE_URL
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
