apiVersion: v1
kind: Secret
metadata:
  name: wioleet-secrets
labels:
    draft: {{ default "draft-app" .Values.draft }}
    app: {{ template "fullname" . }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}